
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://13.127.157.211:3306/userdatabase
    username: dev
    password: 7777

server:
  port: 9000

security:
  jwt:
    login-uri: /login
    header: Authorization
    prefix: Bearer
    expiration: 86400 #{24*60*60}
    secret: FrostLoginSecret
