
spring:
  application:
    name: login-service

#  resources:
#    add-mappings: false
#  mvc:
#    throw-exception-if-no-handler-found: true

  profiles:
    active: dev
#    active: ui
#    active: test

